const minute = {
  '01': 'oh one',
  '02': 'oh two',
  '03': 'oh three',
  '04': 'oh four',
  '05': 'five',
  '06': 'oh six',
  '07': 'oh seven',
  '08': 'oh eight',
  '09': 'oh nine',
  '10': 'ten',
  '11': 'eleven',
  '12': 'twelve',
  '13': 'thirteen',
  '14': 'fourteen',
  '15': 'quarter',
  '16': 'sixteen',
  '17': 'seventeen',
  '18': 'eighteen',
  '19': 'nineteen',
  '20': 'twenty',
  '21': 'twenty-one',
  '22': 'twenty-two',
  '23': 'twenty-three',
  '24': 'twenty-four',
  '25': 'twenty-five',
  '26': 'twenty-six',
  '27': 'twenty-seven',
  '28': 'twenty-eight',
  '29': 'twenty-nine',
  '30': 'half',
  '31': 'thirty-one',
  '32': 'thirty-two',
  '33': 'thirty-three',
  '34': 'thirty-four',
  '35': 'thirty-five',
  '36': 'thirty-six',
  '37': 'thirty-seven',
  '38': 'thirty-eight',
  '39': 'thirty-nine',
  '40': 'twenty',
  '41': 'fourty-one',
  '42': 'fourty-two',
  '43': 'fourty-three',
  '44': 'fourty-four',
  '45': 'quarter',
  '46': 'fourty-six',
  '47': 'fourty-seven',
  '48': 'fourty-eight',
  '49': 'fourty-nine',
  '50': 'ten',
  '51': 'fifty-one',
  '52': 'fifty-two',
  '53': 'fifty-three',
  '54': 'fifty-four',
  '55': 'five',
  '56': 'fifty-six',
  '57': 'fifty-seven',
  '58': 'fifty-eight',
  '59': 'fifty-nine',
}

module.exports = minute;